repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/PyCQA/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        args: ["--max-line-length=131", "--ignore=F401,E221,E501,E203,E731,W503,W605"]
        exclude: "sbin"
# -   repo: https://github.com/mgedmin/check-manifest
#     rev: "0.47"
#     hooks:
#     -   id: check-manifest
