# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: astronet

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7
  - absl-py
  - google-pasta==0.2.0
  - cudatoolkit=11
  - cudnn=8.1
  - cupti=11
  - sncosmo

  - pip:
    - astropy>=1.1.2
    - gast==0.3.3
    - george==0.3.1
    - imageio==2.9.0
    - imbalanced-learn==0.7.0
    - jax[cpu]
    - jaxlib
    - joblib==0.17.0
    - jupyter-client>=5.3.4
    - jupyter-console>=6.1.0
    - jupyter-core>=4.6.1
    - jupyter>=1.0.0
    - matplotlib==3.3.2
    - mkdocs
    - nbval
    - numpy==1.19.2
    - optuna==2.3.0
    - pandas==1.1.4
    - pep517
    - plotly==4.12.0
    - pyarrow==2.0.0
    - pybind11==2.6.1
    - pytest
    - pytest-cov
    - pytest-subtests
    - requests
    - scikit-learn==0.23.2
    - scipy>=1.5.0
    - seaborn==0.11.0
    - tensorflow==2.4.1
    - twine
    - xgboost==1.2.1
    - -r requirements.txt
