# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: astronet

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7

  - pip:
    - pytest
    - pep517
    - twine
    - -r file:requirements.txt
