# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: astronet

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.8
  - absl-py
  - google-pasta==0.2.0
  - grpcio
  # - cudatoolkit=11
  # - cudnn=8.1
  # - cupti=11
  - psutil
  - pyregion
  - pyzmq
  - sncosmo

  - pip:
    - astropy>=1.1.2
    - filelock
    - gast==0.3.3
    - imageio>=2.9.0
    - jax[cpu]
    - jaxlib
    - jupyter-client>=5.3.4
    - jupyter-console>=6.1.0
    - jupyter-core>=4.6.1
    - jupyter>=1.0.0
    - matplotlib
    - model-profiler
    - mkdocs
    - nbmake
    - nbval
    - pep517
    - plotly==4.12.0
    - pyarrow>=2.0.0
    - pybind11>=2.6.1
    - pytest
    - pytest-cov
    - pytest-mpl
    - pytest-xdist
    - pytest-subtests
    - requests
    - twine
    - -r requirements.txt
