# This file may be used to create an environment using:
# $ conda env create --name <env> --file <this file>
# platform: linux-64
name: astronet

channels:
  - conda-forge

dependencies:
  - pip
  - python=3.7
  - absl-py
  - google-pasta==0.2.0
  - cudatoolkit=11
  - cudnn=8.1
  - cupti=11
  - sncosmo

  - pip:
    - black==22.1.0
    - black[jupyter]
    - nbval
    - pytest
    - pytest-cov
    - pytest-subtests
    - pep517
    - twine
    - -r requirements.txt
