name: "Check Manifest"

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - issues/69/refactor
  pull_request:
    branches:
      - master

jobs:
  check:
    # Don't run on forks
    if: github.repository == 'tallamjr/astronet'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: Install dependencies
        # scipy and cython are required to build sdist
        run: |
          python -m pip install --upgrade pip
          pip install check-manifest
      - run: |
          check-manifest --verbose
