name: Flake8

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
      - issues/69/refactor
  pull_request:
    branches:
      - master

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
        with:
          ignore: "F401,E221,E501,E203,E731,W503,W605"
          exclude: "${{ github.workspace }}/astronet/datasets.py,${{ github.workspace }}/astronet/tests/reg/lnprofile.py"
          path: "${{ github.workspace }}/astronet"
