name: pytest CI

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - issues/8/test-cov
   pull_request:
     branches:
       - master

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Run pytest
      run: |
        pytest --cov astronet/t2/tests/
