name: PyTest

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false
      matrix:
        name: [
          ubuntu-gcc-py38,
          ]

        include:
          - name: ubuntu-gcc-py38
            os: ubuntu-latest
            compiler: gcc-11

    steps:
    - name: Checkout astronet
      uses: actions/checkout@master

    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8

    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: astronet
        environment-file: environment.yml
        python-version: 3.8
        auto-activate-base: false

    - shell: bash -l {0}
      run: |
        conda info
        conda list

    - name: Check Environment
      run: |
        echo $PWD
        ls -la ${{ github.workspace }}/astronet/tests/
        echo $HOME
        which python
        which pip
        python --version
        echo $PATH
        PATH="/usr/share/miniconda/envs/astronet/bin:$PATH"
        which python
        which pip
        which pytest
        python --version

    - name: Install dependencies
      run: |
        export CC=`which gcc-11`
        export CXX=`which g++-11`
        conda env update --file ${{ github.workspace }}/environment.yml
        PATH="/usr/share/miniconda/envs/astronet/bin:$PATH"
        pip install --upgrade pip
        pip install .

    - name: Run pytest
      run: |
        PATH="/usr/share/miniconda/envs/astronet/bin:$PATH"
        pytest .
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
