name: Test Suite with Code Coverage

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - __master
   pull_request:
     branches:
       - __master

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: astronet
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Check Environment
      run: |
        echo $PWD
        ls -la ${{ github.workspace }}/astronet/t2/tests/
        echo $HOME
        which python
        which pip
        python --version
        echo $PATH
        PATH="/usr/share/miniconda/envs/astronet/bin:$PATH"
        which python
        which pip
        python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pytest
        pip install pytest-cov
    - name: Run pytest
      run: |
        pytest --cov astronet/t2/tests/
