name: TensorFlow CI

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - issues/8/test-cov
   pull_request:
     branches:
       - master

jobs:
  tensorflow:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # - name: Set up Python 3.7
    #   uses: actions/setup-python@v1
    #   with:
    #     python-version: 3.7
    - uses: conda-incubator/setup-miniconda@v1
      with:
        activate-environment: astronet
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false
    - shell: bash -l {0}
      run: |
        conda info
        conda list
        # conda env create -q
        # conda activate astronet
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
    - name: Check Environment
      run: |
        echo $PWD
        ls -la ${{ github.workspace }}/astronet/t2/tests/
        echo $HOME
        which python
        which pip
        python --version
    - name: Run TensorFlow TestCase
      run: |
        python ${{ github.workspace }}/astronet/t2/tests/tf_test_dense_layer.py
        python ${{ github.workspace }}/astronet/t2/tests/tf_test_multihead_attention.py
