name: Check Actions

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - issues/8/test-cov
   pull_request:
     branches:
       - master

jobs:
  actions-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Check Environment
      run: |
        echo $PWD
        ls -la ${{ github.workspace }}/astronet/
        ls -la $PWD/astronet/
        echo $HOME
        ls -la $HOME
