name: Jupyter Notebooks

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tutorials:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    env:
      PYTHON_VERSION: "3.7"
      RUN_CMD: ""

    strategy:
      # Prevent all build to stop if a single one fails
      fail-fast: false
      matrix:
        name: [
          nb-ubuntu-gcc-py37,
          nb-osx-gcc-py37,
          nb-osx-clang-py37,
          ]

        include:
          - name: nb-ubuntu-gcc-py37
            os: ubuntu-16.04
            compiler: gcc-7

          - name: nb-osx-gcc-py37
            os: macos-latest
            compiler: gcc-9

          - name: nb-osx-clang-py37
            os: macos-latest
            compiler: clang

    steps:
    - name: Checkout astronet
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install compilers for OSX
      if: runner.os == 'macOS'
      run: |
        if [ "${{ matrix.compiler }}" = "gcc-9" ]; then
          brew install gcc
        else
          sudo xcode-select -s /Applications/Xcode_11.app/Contents/Developer
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install matplotlib

    - name: Mini-Analysis Pipeline
      run: |
        pytest --nbval notebooks/T2-Mini-Analysis-Pipeline.ipynb
